### PR TITLE
Added Dangerfile and danger step to Travis build

### PR DESCRIPTION
**Pull request by gdavison**
Added `Dangerfile` and `danger` step to Travis build

`Dangerfile` copied from https://github.com/sous-chefs/haproxy

### CODE REVIEW

**Comment by gdavison** [comment]
## Danger has errored
[!] Invalid `Dangerfile` file: Please provide a summary of your Pull Request.
```
 #  from Dangerfile:26
 #  -------------------------------------------
 #  
 >  raise 'Please provide a summary of your Pull Request.' if github.pr_body.length < 10
 #  
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
I'll have to setup the Travis environment vars for this.

If you want to this run reliably, then I would recommend switching at least the danger portion to circleci

**Comment by gdavison** [comment]
@damacus I used a key added to my own account, for now. Is there a general plan to move to circleci? I basically copied the Danger setup from https://github.com/sous-chefs/haproxy

**Comment by damacus** [comment]
If I get the time or inclination circleci or something else. The second one
depends on me getting my hands on something special!

**Review by damacus — APPROVED** [review]

**Pull request merged**
